import { TreeLeaf, TreeNode } from "@/lib/assetsTree";
import { LocationData, AssetData } from "@/services/companies";

export const locations: LocationData[] = [
  {
    id: "1",
    name: "Location A",
    parentId: "4",
  },
  {
    id: "2",
    name: "Location B",
    parentId: null,
  },
  {
    id: "3",
    name: "Location C",
    parentId: null,
  },
  {
    id: "4",
    name: "Location D",
    parentId: null,
  },
];

export const assets: AssetData[] = [
  {
    id: "5",
    locationId: "1",
    name: "Asset 1",
    parentId: null,
    sensorType: null,
    status: null,
    gatewayId: null,
    sensorId: null,
  },
  {
    gatewayId: "QHI640",
    id: "6",
    locationId: null,
    name: "Component 1",
    parentId: null,
    sensorId: "MTC052",
    sensorType: "energy",
    status: "operating",
  },
  {
    id: "7",
    locationId: "3",
    name: "Asset 2",
    parentId: null,
    sensorType: null,
    status: null,
    gatewayId: null,
    sensorId: null,
  },
  {
    gatewayId: "FRH546",
    id: "8",
    locationId: null,
    name: "Component 2",
    parentId: "9",
    sensorId: "FIJ309",
    sensorType: "vibration",
    status: "operating",
  },
  {
    id: "9",
    locationId: null,
    name: "Asset 3",
    parentId: "5",
    sensorType: null,
    status: null,
    gatewayId: null,
    sensorId: null,
  },
  {
    gatewayId: "QBK282",
    id: "10",
    locationId: null,
    name: "Component 3",
    parentId: "13",
    sensorId: "CFX848",
    sensorType: "vibration",
    status: "alert",
  },
  {
    gatewayId: "VHS387",
    id: "11",
    locationId: null,
    name: "Component 4",
    parentId: "13",
    sensorId: "GYB119",
    sensorType: "vibration",
    status: "alert",
  },
  {
    gatewayId: "VZO694",
    id: "12",
    locationId: null,
    name: "Component 5",
    parentId: "13",
    sensorId: "SIF016",
    sensorType: "vibration",
    status: "alert",
  },
  {
    id: "13",
    locationId: "3",
    name: "Asset 4",
    parentId: null,
    sensorType: null,
    status: null,
    gatewayId: null,
    sensorId: null,
  },
];

export const treeList: Array<TreeNode | TreeLeaf> = [
  {
    id: "2",
    name: "Location B",
    parentId: null,
    type: "location",
    children: [],
    path: new Map([["2", "Location B"]]),
  },
  {
    id: "3",
    name: "Location C",
    parentId: null,
    type: "location",
    children: [
      {
        id: "7",
        locationId: "3",
        name: "Asset 2",
        parentId: null,
        sensorType: null,
        status: null,
        gatewayId: null,
        sensorId: null,
        type: "asset",
        children: [],
        path: new Map([
          ["3", "Location C"],
          ["7", "Asset 2"],
        ]),
      },
      {
        id: "13",
        locationId: "3",
        name: "Asset 4",
        parentId: null,
        sensorType: null,
        status: null,
        gatewayId: null,
        sensorId: null,
        type: "asset",
        path: new Map([
          ["3", "Location C"],
          ["13", "Asset 4"],
        ]),
        children: [
          {
            gatewayId: "QBK282",
            id: "10",
            locationId: null,
            name: "Component 3",
            parentId: "13",
            sensorId: "CFX848",
            sensorType: "vibration",
            status: "alert",
            type: "component",
            path: new Map([
              ["3", "Location C"],
              ["13", "Asset 4"],
              ["10", "Component 3"],
            ]),
          },
          {
            gatewayId: "VHS387",
            id: "11",
            locationId: null,
            name: "Component 4",
            parentId: "13",
            sensorId: "GYB119",
            sensorType: "vibration",
            status: "alert",
            type: "component",
            path: new Map([
              ["3", "Location C"],
              ["13", "Asset 4"],
              ["11", "Component 4"],
            ]),
          },
          {
            gatewayId: "VZO694",
            id: "12",
            locationId: null,
            name: "Component 5",
            parentId: "13",
            sensorId: "SIF016",
            sensorType: "vibration",
            status: "alert",
            type: "component",
            path: new Map([
              ["3", "Location C"],
              ["13", "Asset 4"],
              ["12", "Component 5"],
            ]),
          },
        ],
      },
    ],
    path: new Map([["3", "Location C"]]),
  },
  {
    id: "4",
    name: "Location D",
    parentId: null,
    type: "location",
    children: [
      {
        id: "1",
        name: "Location A",
        parentId: "4",
        type: "location",
        children: [
          {
            id: "5",
            locationId: "1",
            name: "Asset 1",
            parentId: null,
            sensorType: null,
            status: null,
            gatewayId: null,
            sensorId: null,
            type: "asset",
            path: new Map([
              ["4", "Location D"],
              ["1", "Location A"],
              ["5", "Asset 1"],
            ]),
            children: [
              {
                id: "9",
                locationId: null,
                name: "Asset 3",
                parentId: "5",
                sensorType: null,
                status: null,
                gatewayId: null,
                sensorId: null,
                type: "asset",
                path: new Map([
                  ["4", "Location D"],
                  ["1", "Location A"],
                  ["5", "Asset 1"],
                  ["9", "Asset 3"],
                ]),
                children: [
                  {
                    gatewayId: "FRH546",
                    id: "8",
                    locationId: null,
                    name: "Component 2",
                    parentId: "9",
                    sensorId: "FIJ309",
                    sensorType: "vibration",
                    status: "operating",
                    type: "component",
                    path: new Map([
                      ["4", "Location D"],
                      ["1", "Location A"],
                      ["5", "Asset 1"],
                      ["9", "Asset 3"],
                      ["8", "Component 2"],
                    ]),
                  },
                ],
              },
            ],
          },
        ],
        path: new Map([
          ["4", "Location D"],
          ["1", "Location A"],
        ]),
      },
    ],
    path: new Map([["4", "Location D"]]),
  },
  {
    gatewayId: "QHI640",
    id: "6",
    locationId: null,
    name: "Component 1",
    parentId: null,
    sensorId: "MTC052",
    sensorType: "energy",
    status: "operating",
    type: "component",
    path: new Map([["6", "Component 1"]]),
  },
];

export const tree: TreeNode | TreeLeaf = {
  id: "3",
  name: "Location C",
  parentId: null,
  type: "location",
  path: new Map([["3", "Location C"]]),
  children: [
    {
      id: "7",
      locationId: "3",
      name: "Asset 2",
      parentId: null,
      sensorType: null,
      status: null,
      gatewayId: null,
      sensorId: null,
      type: "asset",
      children: [],
      path: new Map(),
    },
    {
      id: "13",
      locationId: "3",
      name: "Asset 4",
      parentId: null,
      sensorType: null,
      status: null,
      gatewayId: null,
      sensorId: null,
      type: "asset",
      path: new Map([
        ["3", "Location C"],
        ["13", "Asset 4"],
      ]),
      children: [
        {
          gatewayId: "QBK282",
          id: "10",
          locationId: null,
          name: "Component 3",
          parentId: "13",
          sensorId: "CFX848",
          sensorType: "vibration",
          status: "alert",
          type: "component",
          path: new Map([
            ["3", "Location C"],
            ["13", "Asset 4"],
            ["10", "Component 3"],
          ]),
        },
        {
          gatewayId: "VHS387",
          id: "11",
          locationId: null,
          name: "Component 4",
          parentId: "13",
          sensorId: "GYB119",
          sensorType: "vibration",
          status: "alert",
          type: "component",
          path: new Map([
            ["3", "Location C"],
            ["13", "Asset 4"],
            ["11", "Component 4"],
          ]),
        },
        {
          gatewayId: "VZO694",
          id: "12",
          locationId: null,
          name: "Component 5",
          parentId: "13",
          sensorId: "SIF016",
          sensorType: "vibration",
          status: "alert",
          type: "component",
          path: new Map([
            ["3", "Location C"],
            ["13", "Asset 4"],
            ["12", "Component 5"],
          ]),
        },
      ],
    },
  ],
};

// filter node.status === "alert"
export const filteredTreeList: Array<TreeNode | TreeLeaf> = [
  {
    id: "3",
    name: "Location C",
    parentId: null,
    type: "location",
    children: [
      {
        id: "13",
        locationId: "3",
        name: "Asset 4",
        parentId: null,
        sensorType: null,
        status: null,
        gatewayId: null,
        sensorId: null,
        type: "asset",
        path: new Map([
          ["3", "Location C"],
          ["13", "Asset 4"],
        ]),
        children: [
          {
            gatewayId: "QBK282",
            id: "10",
            locationId: null,
            name: "Component 3",
            parentId: "13",
            sensorId: "CFX848",
            sensorType: "vibration",
            status: "alert",
            type: "component",
            path: new Map([
              ["3", "Location C"],
              ["13", "Asset 4"],
              ["10", "Component 3"],
            ]),
          },
          {
            gatewayId: "VHS387",
            id: "11",
            locationId: null,
            name: "Component 4",
            parentId: "13",
            sensorId: "GYB119",
            sensorType: "vibration",
            status: "alert",
            type: "component",
            path: new Map([
              ["3", "Location C"],
              ["13", "Asset 4"],
              ["11", "Component 4"],
            ]),
          },
          {
            gatewayId: "VZO694",
            id: "12",
            locationId: null,
            name: "Component 5",
            parentId: "13",
            sensorId: "SIF016",
            sensorType: "vibration",
            status: "alert",
            type: "component",
            path: new Map([
              ["3", "Location C"],
              ["13", "Asset 4"],
              ["12", "Component 5"],
            ]),
          },
        ],
      },
    ],
    path: new Map([["3", "Location C"]]),
  },
];
