import type { Metadata } from "next";
import { Inter } from "next/font/google";

// import "./globals.scss";
import Header from "@/components/Header/Header";

export const metadata: Metadata = {
  title: "Tractian",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}>
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
