import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.scss";

import Header from "@/components/Header/Header";

import styles from "./layout.module.scss";

export const metadata: Metadata = {
  title: "Tractian",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}>
      <body>
        <Header />
        <main className={styles.main}>{children}</main>
      </body>
    </html>
  );
}
